{{ config(materialized='view') }}
 
SELECT
    loan.NAME AS LOAN_NAME,
    acct.NAME AS ACCOUNT_NAME,
    acct.EXTERNAL_ID AS ACCOUNT_EXTERNAL_ID,
    SUM(CAST(line.NET_AMOUNT AS NUMBER(18,2))) AS TOTAL_NET_AMOUNT
FROM LEGACY_RDA.REPORTING.NETSUITE_ACCOUNT_LATEST AS acct
JOIN LEGACY_RDA.REPORTING.NETSUITE_TRANSACTION_LINE_LATEST AS line
    ON acct.ID = line.EXPENSE_ACCOUNT_ID
JOIN LEGACY_RDA.REPORTING.NETSUITE_LOAN_LATEST AS loan
    ON loan.ID = line.LOAN_ID
GROUP BY
    loan.NAME,
    acct.NAME,
    acct.EXTERNAL_ID